server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Servir arquivos estáticos
    location / {
        try_files $uri /index.html;
    }

    # Proxy para /backend com barra final
    location /backend/ {
        rewrite ^/backend(/.*)$ $1 break;    # Remove o prefixo /backend da URL
        proxy_pass http://backend:8000/;      # Redireciona para o backend em localhost:8000
        proxy_set_header Host $host;          # Define o cabeçalho Host
        proxy_set_header X-Real-IP $remote_addr;    # Envia o IP real do cliente
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Cabeçalhos de proxy
        proxy_set_header X-Forwarded-Proto $scheme;  # Esquema HTTP ou HTTPS
        proxy_set_header Accept-Encoding "";       # Remove a compressão de resposta para evitar problemas com o JSON
        proxy_set_header Accept "application/json"; # Força o cabeçalho de aceitação de JSON
        proxy_http_version 1.1;                   # Garante que a comunicação seja feita com HTTP/1.1
        proxy_set_header Connection '';           # Garante a persistência da conexão
    }

    # Adicionando barra final para /backend sem barra
    location ~ ^/backend$ {
        return 301 /backend/;  # Redireciona para /backend/ com a barra
    }

    # Adicionando barra final para qualquer URL /backend/xxxx sem barra
    location ~ ^/backend/[^/]+$ {
        return 301 $uri/;  # Redireciona para a versão com barra final
    }

    # Cache para arquivos estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Gzip para melhorar a performance
    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # Logs de erro e acesso (opcional)
    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
}
