stages:
  - prepare
  - test
  - security

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

# Rebase com develop se não for a própria develop
rebase_develop:
  stage: prepare
  image: alpine:latest
  script:
    - apk add --no-cache git
    - echo "Estamos atualmente na branch $CI_COMMIT_REF_NAME"
    - git config --global user.email "miguelgoncalves2024@hotmail.com"
    - git config --global user.name "miguelgoncalves2024"
    - git fetch --unshallow || true
    - >
      if [ "$CI_COMMIT_REF_NAME" != "develop" ]; then
        git rebase origin/develop || exit 1;
      else
        echo "Já estamos na branch develop. Nenhum rebase necessário.";
      fi

# Backend Security Check
python_test:
  image: python:3.12-slim
  stage: security
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc libmariadb-dev pkg-config curl git && rm -rf /var/lib/apt/lists/*
    - cd backend
    - rm -rf .venv/
    - python -m venv .venv
    - . .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install bandit
    - bandit -r . -c bandit.yml --exclude ./startBackend.py
  allow_failure: true

# Frontend Security Check
node_test:
  image: node:22.14.0-alpine3.20
  stage: security
  script:
    - cd frontend
    - npm install
    - npm audit --audit-level=high || true
  allow_failure: true
