stages:
  - prepare
  - test
  - security

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

# Rebase com develop se não for a própria develop
merge_develop:
  stage: prepare
  image: alpine:latest
  script:
    - apk add --no-cache git
    - echo "Estamos atualmente na branch $CI_COMMIT_REF_NAME"
    - git config --global user.email "miguelgoncalves2024@hotmail.com"
    - git config --global user.name "miguelgoncalves2024"
    - git fetch --unshallow || true
    - >
      if [ "$CI_COMMIT_REF_NAME" != "develop" ] && [ "$CI_COMMIT_REF_NAME" != "main" ]; then
        git merge origin/develop || exit 1;
      else
        echo "Estamos na branch $CI_COMMIT_REF_NAME. Nenhum merge necessário.";
      fi

# Backend Security Check
python_test:
  image: python:3.14-slim
  stage: security
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc libmariadb-dev pkg-config curl git && rm -rf /var/lib/apt/lists/*
    - cd backend
    - rm -rf .venv/
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv venv
    - . .venv/bin/activate
    - uv pip install --upgrade pip
    - uv pip install -r pyproject.toml
    - uv add bandit
    - bandit -r . --exclude ./tests,./migrations,./venv,./.venv,./docs,./__pycache__,./controller
  allow_failure: true

# Frontend Security Check
node_test:
  image: node:24-alpine
  stage: security
  script:
    - cd frontend
    - npm install
    - npm audit --audit-level=high || true
  allow_failure: true
