stages:
  - test
  - security

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

# Backend Security Check
python_test:
  image: python:3.12-slim
  stage: security
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc libmariadb-dev pkg-config curl git && rm -rf /var/lib/apt/lists/*
    
    - cd backend
    - rm -rf .venv/
    - python -m venv .venv
    - . .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install safety bandit

    - bandit -r . -c bandit.yml
    - safety scan --full-report --severity=high --api-key=$SAFETY_API_KEY || true  # Permite falhas
  allow_failure: true  # Continua o pipeline mesmo com falhas

# Frontend Security Check
node_test:
  image: node:22.14.0-alpine3.20
  stage: security
  script:
    - cd frontend
    - npm install
    - npm audit --audit-level=high || true  # Permite falhas
  allow_failure: true  # Continua o pipeline mesmo com falhas
