services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    networks:
      - app_network # Backend está acessível apenas dentro da rede Docker

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80" # Porta exposta para acessar o frontend
    networks:
      - app_network
    depends_on:
      - backend # Garante que o backend seja iniciado antes do frontend

networks:
  app_network:
    driver: bridge # Rede bridge para comunicação interna
