[project]
name = "backend"
version = "1.5.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.2",
    "argon2-cffi>=25.1.0",
    "brevo-python>=1.2.0",
    "dotenv>=0.9.9",
    "fastapi>=0.129.0",
    "filetype>=1.2.0",
    "firebase-admin>=7.1.0",
    "httpx>=0.28.1",
    "motor>=3.7.1",
    "passlib>=1.7.4",
    "pydantic[email]>=2.12.5",
    "pyjwt>=2.11.0",
    "redis>=7.2.0",
    "strawberry-graphql>=0.296.2",
    "stripe>=14.3.0",
    "uvicorn>=0.41.0",
    "weasyprint>=68.1",
]
[tool.black]
line-length = 150
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
(
    (^|/)(\.venv|venv)
  | ^build/
  | ^dist/
  | ^migrations/
  | ^__pycache__/
)
'''
